### PR TITLE
Pulseaudio/readability

### PR DESCRIPTION
**Pull request by dalgwen**
(See comment in the source openhad pull request)

### CODE REVIEW

**Comment by GiviMAD** [comment]
Hello @dalgwen the changes seems great for me unless the for the PipedAudioStream.

I want a way to sent infinite realtime PCM audio, that is why the PipedAudioStream exposed the onClose method to be able subscribe to its end and you are removing the use of that method with your PR so for me it partially breaks what I was trying to accomplish. Also as it will be infinite (it will not have a defined length) trying to measure it is useless and will create overhead. So I will prefer to split how the PipedAudioStream is handled because it was created for a specific use case.

Do you think you can rollback that part from the PR?

**Comment by GiviMAD** [comment]
I was thinking on it and just handing on a special way the case where the stream has PCM_FORMAT and is PipedAudioStream should be enough for me.

Because there are two use cases I have in mind for the PipedAudioStream:
* Connect a source to a sink, and all the sources we have emit PCM audio.
* Implement some kind of music player, and in that case I will handle the format conversion on one place and emit pcm audio to the sinks.

So for me if we can reinsert the piped audio block before using the ConvertedAudioStream just for that specific case that will be enough.

**Comment by dalgwen** [comment]
Hello, @GiviMAD 

> I want a way to sent infinite realtime PCM audio, that is why the PipedAudioStream exposed the onClose method to be able subscribe to its end and you are removing the use of that method with your PR so for me it partially breaks what I was trying to accomplish. Also as it will be infinite (it will not have a defined length) trying to measure it is useless and will create overhead. So I will prefer to split how the PipedAudioStream is handled because it was created for a specific use case.

AFAIK, the infinite stream is not an issue, the code in this MR handles it the same way as yours.

If you look inside the transferAndAnalyzeLength method, you will see that it uses internally the InputStream.transfertTo method, which is EXACTLY what you do in you custom code (while, read >=0, write). (You should use it by the way, it is easier to read and less error prone). And this may block by reading/writing indefinitely, no problem, because it is now fully async in another thread, for all cases.
This method also counts the nb of byte transfered in a long variable, which is really absolutely no overhead at all (the AtomicBoolean you use is thousand of times more costly). And you won't come to the Long limit unless you want to run it to the end of the universe 😅

And your second concern is the callback : I still don't understand why you want to add a this callback to you stream when it ends ?
The callback you add makes two operations : 
- releasing module (which is done in this MR by calling endStream, whether the transfer finished OK or with an IO Exception when stream closed), so no need.
- Setting cancel to true, which, as far as I understand, has no utility either. Setting cancel to true has only one use : interrupt the read loop. BUT, the onClose callback is called when the stream is closed. And in PipedInputStream, when the stream is closed, you set a boolean to false, and this boolean force all further read operation to return -1. And reading -1 is effectively ending the loop.
So your double OR condition to break the loop is not necessary : every time cancel is set to true, the reading operation should also return -1, effectively breaking the loop the same way, on the same iteration.

**Comment by dalgwen** [comment]
> I was thinking on it and just handing on a special way the case where the stream has PCM_FORMAT and is PipedAudioStream should be enough for me.

I still don't think that it is necessary : I think it will work altogether without the need of special cases.
(And I really really think that openHAB audio sink shouldn't have to make special adjustement to read an InputStream depending on the implementation. Your use case is a pretty standard use of InputStream, and can be handled without relying on detecting the  specific implementation)

> Because there are two use cases I have in mind for the PipedAudioStream:

 
>     * Connect a source to a sink, and all the sources we have emit PCM audio.
> 
>     * Implement some kind of music player, and in that case I will handle the format conversion on one place and emit pcm audio to the sinks.

Do you have something to test ? I would be happy to check if the code in this MR is OK (unless there is some bugs, I really think the concept here are OK.

**Comment by GiviMAD** [comment]
Ok, I'll merge it as is then, I see that with the current method for measuring the audio duration my concerns are unfunded. Thank you for the explanation and the code changes, it is far more readable now.

**Pull request merged**
